-- Recursos
INSERT INTO RECURSO (NOMBRE, DESCRIPCION) VALUES ('Proyector', 'Un proyector HD');
INSERT INTO RECURSO (NOMBRE, DESCRIPCION) VALUES ('Pizarrón', 'Color negro');
INSERT INTO RECURSO (NOMBRE, DESCRIPCION) VALUES ('Silla', 'Con cuatro pata');
INSERT INTO RECURSO (NOMBRE, DESCRIPCION) VALUES ('Sillón', 'Color marrón');

-- Espacio Fisico
INSERT INTO ESPACIO_FISICO (NOMBRE, CAPACIDAD, DESCRIPCION, HABILITADO) VALUES ('Espacio 1', 20, '...', true);
INSERT INTO ESPACIO_FISICO (NOMBRE, CAPACIDAD, DESCRIPCION, HABILITADO) VALUES ('Espacio 2', 20, '...', true);
INSERT INTO ESPACIO_FISICO (NOMBRE, CAPACIDAD, DESCRIPCION, HABILITADO) VALUES ('Espacio 3', 20, '...', true);
INSERT INTO ESPACIO_FISICO (NOMBRE, CAPACIDAD, DESCRIPCION, HABILITADO) VALUES ('Espacio 4', 20, '...', true);
INSERT INTO ESPACIO_FISICO (NOMBRE, CAPACIDAD, DESCRIPCION, HABILITADO) VALUES ('Espacio 5', 20, '...', true);

-- Recursos del Espacio Físico
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (1, 1);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (1, 2);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (1, 3);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (2, 2);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (3, 3);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (4, 4);
INSERT INTO ESPACIO_FISICO_RECURSOS (ESPACIO_FISICO_ID, RECURSOS_ID) VALUES (5, 4);

-- Estados
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Creado', 'La reserva fue creada de manera exitosa.', 'FFA500');
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Reservado', 'La reserva quedo grabada correctamente.', '008000');
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Pendiente', 'La reserva está pendiente.', 'FFD700');
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Cancelada', 'La reserva fue cancelada.', 'FF0000');
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Completada', 'La reserva fue completada.', '00FF00');
INSERT INTO ESTADO (NOMBRE, DESCRIPCION, COLOR) VALUES ('Bloqueada', 'La reserva fue bloqueada.', '800000');

--